- name: Deploy Maven Artifact
  hosts: local
  tasks:
    - name: Copy artifact
      copy:
        src: "{{ workspace }}/target/*.jar"
        dest: /home/sohamgupta/selenium/HelloMaven/deploy
        remote_src: yes
