- name: Deploy Maven Artifact
  hosts: all
  vars:
    target_dir: "{{ ansible_env.PWD }}/../target"
    deploy_dir: "{{ ansible_env.PWD }}"
  tasks:
    - name: Find .jar files
      find:
        paths: "{{ target_dir }}"
        patterns: "*.jar"
      register: found_jars

    - name: Copy artifact(s)
      copy:
        src: "{{ item.path }}"
        dest: "{{ deploy_dir }}/"
      loop: "{{ found_jars.files }}"
