- name: Deploy Maven Artifact
  hosts: all
  tasks:
    - name: Find .jar files
      find:
        paths: /home/sohamgupta/jenkins_home/workspace/HelloMaven/target
        patterns: "*.jar"
      register: found_jars

    - name: Copy artifact(s)
      copy:
        src: "{{ item.path }}"
        dest: /home/sohamgupta/selenium/HelloMaven/deploy/
      with_items: "{{ found_jars.files }}"
