- name: Deploy Maven Artifact
  hosts: local
  tasks:
    - name: Copy artifact
      copy:
        src: /home/sohamgupta/jenkins_home/workspace/HelloMaven/target/*.jar
        dest: /home/sohamgupta/selenium/HelloMaven/deploy
        remote_src: yes
